numpy通常以np的名字导入

In [1]:
import numpy as np

numpy用数组array来进行计算  
现在我们准备一个numpy的array，它的元素是[1,2,3,4,5]

In [2]:
arr = np.array([1, 2, 3, 4, 5])

可以通过shape查看它的大小

In [3]:
arr.shape

(5,)

对array做加法运算

In [4]:
arr + 2

array([3, 4, 5, 6, 7])

所有的元素都被+2了 
我们称之为广播

不仅仅是加法运算，其他运算也会发生同样的事情  
我们试着操作一下

In [5]:
np.sqrt(arr)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798])

和列表一样，你可以在切片中提取元素  

In [6]:
arr[:2]

array([1, 2])

In [7]:
arr[3:5]

array([4, 5])

我们经常使用numpy的arange函数  
可以使用arange函数来创建带有[0,1,2,3,4]元素的array

In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

可以在arange函数中指定start, end, step  
[2, 4, 6, 8]这个以数字2递增的array可以是这样的

In [9]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

我们也经常使用linspace函数  
linspace函数也是制作从开始到结束的array的函数，但不是step，而是指定元素的数量  
现在，我们将0到3分成11个array

In [10]:
np.linspace(0, 3, 11)

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8,  2.1,  2.4,  2.7,  3. ])

二维的array也很容易制作

In [11]:
arr2 = np.array([[1, 3],
                 [5, 7]])
arr2

array([[1, 3],
       [5, 7]])

In [12]:
arr2.shape

(2, 2)

可以用save函数保存array  
第一个参数是保存的名字，第二个参数是保存的array

In [13]:
np.save('test.npy', arr2)

它可以通过load函数来读取

In [14]:
np.load('test.npy')

array([[1, 3],
       [5, 7]])